name: ci

on:
  push:
    branches:
      - version-15-prod

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: nxmaydogdu/erpnext-nx:test
          file: ./Containerfile
          build-args: APPS_JSON_BASE64=${{ secrets.APPS_JSON_BASE64 }}
          no-cache: true
